# Meta Data for SEO

## Homepage
title = "NivelDev"
titleSeparator = "-"
titleAddition = "Programa tu propio juego"
description = "Un Blog para entusiastas de la programación, con muchos ejemplos y documentacion explicada facilmente, para todos lo que deseen aprender. Todo oriendado a Roblox Studio."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "es_ES"
domainTLD = "niveldev.netlify.app"
titleHome = "niveldev"

## Twitter Cards
twitterSite = "@migu3lrg"
twitterCreator = "@migu3lrg"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "NivelDev"
schemaAuthor = "Miguel Romero"
schemaAuthorTwitter = "https://twitter.com/migu3lrg"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/miguelromerog/"
schemaAuthorGitHub = "https://github.com/migu3lr"
schemaLocale = "es-ES"
schemaLogo = "/images/logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "/images/logo.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/migu3lrg"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/migu3lrg"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022-2023 NivelDev"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Suscribete a nuestro canal en YouTube! <a class=\"alert-link stretched-link\" href=\"https://www.youtube.com/c/niveldev?sub_confirmation=1\">Ir a Youtube</a> "

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/Migu3lR/niveldev_blog"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
